apiVersion: v1
kind: Service
metadata:
  name: {{ include "azdo-pipelines-agent.fullname" . }}
  labels:
    {{- include "azdo-pipelines-agent.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "azdo-pipelines-agent.selectorLabels" . | nindent 4 }}
