name: Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.1.0

    - name: Run chart-testing (list-changed)
      working-directory: charts
      id: list-changed
      run: |
        # changed=$(ct list-changed)
        # if [[ -n "$changed" ]]; then
        #   echo "::set-output name=changed::true"
        # fi
        echo "::set-output name=changed::true"

    - name: Run chart-testing (lint)
      working-directory: charts
      run: ct lint

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Crayon"
          git config user.email "crayon@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
